services:
  redis:
    image: redis

pipeline:

  test:
    image: python:2.7
    commands:
      - pip install -r requirements.txt
      - pip install pytest
      - pytest tests.py -s

  deploy-heroku:
    image: fbcbarbosa/heroku
    app: hello-estabilis
    login: fbcbarbosa@gmail.com
    secrets: [ plugin_token ]
    when:
      branch: master

